# Generated by Django 4.1.3 on 2022-11-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('dni', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('tipo_dni', models.CharField(choices=[('cedula', 'cedula'), ('tarjeta de identidad', 'tarjeta de identidad'), ('pasaporte', 'pasaporte')], max_length=20)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino')], max_length=10)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('estado_civil', models.CharField(choices=[('soltero/a', 'soltero/a'), ('casado/a', 'casado/a'), ('viudo/a', 'viudo/a'), ('divorciado/a', 'divorciado')], max_length=12)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('estado_actual', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo'), ('retirado', 'retirado')], max_length=8)),
            ],
            options={
                'db_table': 'afiliado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(choices=[('conyuge', 'conyuge'), ('padre', 'padre'), ('madre', 'madre'), ('hijo/a', 'hijo/a')], max_length=7)),
            ],
            options={
                'db_table': 'beneficiario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibido', models.DateField()),
                ('salario_base', models.IntegerField()),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], max_length=9)),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cotizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cotizante', models.CharField(choices=[('dependiente', 'dependiente'), ('independiente', 'independiente')], max_length=15)),
                ('fecha_primera_afiliacion', models.DateField(auto_now_add=True)),
                ('salario', models.IntegerField()),
                ('rango_salarial', models.CharField(choices=[('A', 'A: < 2 smlv'), ('B', 'B: 2-5 smlv'), ('C', 'C: > 5 smlv')], max_length=1)),
            ],
            options={
                'db_table': 'cotizante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nit_rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=50, unique=True)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('nombre_contacto', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('nit', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=50, unique=True)),
                ('nivel_atencion', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'ips',
                'db_table': 'ips',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IpsServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ips_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('medico', models.CharField(max_length=50)),
                ('diagnostico', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'orden_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagoAportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.IntegerField()),
            ],
            options={
                'db_table': 'pago_aportes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
    ]
